language: php
sudo: false

php:
  - 5.6
  - 5.5
  - 5.4

env:
  - SYMFONY=2.3.*
  - SYMFONY=2.4.*
  - SYMFONY=2.5.*
  - SYMFONY=2.6.*
  - SYMFONY=2.7.*
  - SYMFONY=2.8.*@dev

matrix:
  allow_failures:
    - env: SYMFONY=2.8.*@dev

install:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY} -n

script:
  - bin/phpunit
