language: php
sudo: false

php:
  - 7.1
  - 7.0
  - 5.6

env:
  - SYMFONY=3.3.*@dev
  - SYMFONY=3.2.*
  - SYMFONY=3.1.*
  - SYMFONY=3.0.*

matrix:
  allow_failures:
    - env: SYMFONY=3.3.*@dev

install:
  - composer self-update
  - composer require symfony/form:${SYMFONY} -n

script:
  - bin/phpunit
